INSERT INTO `category` (`id_category`, `nam_category`) VALUES (1,	'telefonia');
INSERT INTO `category` (`id_category`, `nam_category`) VALUES (2,	'game');
INSERT INTO `category` (`id_category`, `nam_category`) VALUES (3,	'Livros');
INSERT INTO `category` (`id_category`, `nam_category`) VALUES (4,	'Eletrodomésticos');

INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (1,	'Moto G5 Plus',	999.00,	1);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (2,	'Ar Samsung Split',	1227.15,	4);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (3,	'Smart TV LED 49',	2999.90,	4);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (4,	'Console Playstation 4 Pro',	2226.90,	2);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (5,	'As crônicas de Nárnia',	15.90,	3);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (6,	'Box Assassin\'s creed vol 1',	49.90,	3);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (7,	'Box Sherlock Holmes 4 vol',	64.00,	3);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (8,	'O nome do vento',	24.50,	3);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (9,	'Pequenas grandes mentiras',	34.92,	3);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (10,	'Galaxy S8',	3999.00,	1);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (11,	'LG X power Dual',	619.99,	1);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (12,	'Mirage 41s',	289.90,	1);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (13,	'Galaxy A3',	799.99,	1);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (14,	'Asus Zenfone 3',	1599.00,	1);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (15,	'Console Playstation 4 Slim',	1194.90,	2);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (16,	'Horizon Zero Dawn - PS4',	169.90,	2);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (17,	'The Last Of Us Remasterizado - PS4',	99.99,	2);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (18,	'Xbox One 500gb',	1399.00,	2);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (19,	'Rise of the Tomb Raider - XBOX One',	89.90,	2);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (20,	'Lavadora de Roupas Electrolux 6kg',	912.51,	4);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (21,	'Geladeira/ Refrigerador Electrolux',	1899.99,	4);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (22,	'Forno Elétrico Philco 36l',	249.00,	4);
INSERT INTO `product` (`id_product`, `nam_product`, `val_product`, `id_category`) VALUES (23,	'Lava e Seca LG Mega Touch 8,5kg',	2199.99,	4);